spring:
    config:
        import: optional:configserver:https://driveshare-backend-aeio.onrender.com
    application: 
        name: gateway-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://driveshare-backend-1.onrender.com/eureka/