spring:
    cloud:
        gateway:   
            discovery:  
                locator:   
                    enabled: true
            routes:
                - id: authentication-service
                  uri: lb://AUTHENTICATION-SERVICE
                  predicates:
                    - Path=/api/v1/auth/**
                - id: authentication-service
                  uri: lb://AUTHENTICATION-SERVICE
                  predicates:
                    - Path=/api/v1/user/**
                - id: reservation-service
                  uri: lb://RESERVATION-SERVICE
                  predicates:
                    - Path=/api/v1/reservations/**
                
server:
    port: 8222

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://driveshare-backend-1.onrender.com/eureka/