spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host-garage.mysql.database.azure.com:3306/host-garage
    username: driveshare
    password: dr1veshare_123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8090
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

application:
  config:
    user-url: https://driveshare-reservationservice.onrender.com/api/v1/