spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reservationDB
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8090
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

application:
  config:
    user-url: http://localhost:8222/api/v1/